### ISSUE TITLE
duplicate header values causing issues 

### ISSUE THREAD

**Issue by aMahanna** [ldbc/data-sets-surf-repository#1]
Hi,

Certain Social Network Benchmark `csv` file have duplicate header names, which can complicate parsing. I am looking for suggestions.
 
Given the following data:
* Dataset: https://repository.surfsara.nl/datasets/cwi/snb/files/social_network-csv_basic/social_network-csv_basic-sf1.tar.zst
* File: `dynamic/person_knows_person_0_0.csv` (there are other multiple cases like this)

```
Person.id|Person.id|creationDate
933|4139|2010-03-13T07:37:21.718+0000
...
```

We run this snippet:

```py
import csv
filepath = 'social_network-csv_basic-sf1/dynamic/person_knows_person_0_0.csv'
with open(filepath, "r") as f:
    data = csv.DictReader(f, delimiter="|")
    for d in data:
        print(d)
```

And observe the following:

```
{'Person.id': '4139', 'creationDate': '2010-03-13T07:37:21.718+0000'}
```

Notice how `Person.id 933` no longer exists.

Looking for suggestions.

**Comment by szarnyasg** [comment]
Hi @aMahanna 

This is a good point. The new datagen's format (https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf#page=27) amends this issue. These data sets are staged to be uploaded but are not yet available -- and their schema is quite different, so they will not work with the LDBC SNB Interactive toolchain.

For the time being, a reasonably efficient way of replacing the headers (by producing a new file) is the following:
```bash
echo "Person1.id|Person2.id|creationDate" | \
  cat - \
  <(tail -n +2 person_knows_person_0_0.csv) \
  > person_knows_person_0_0-new-header.csv
```

You can also use `sed` but it produces a large temporary file in `/tmp` which can run out of disk quickly.

**Comment by aMahanna** [comment]
Good to know, and thank you for the header update snippet 👍
