### ISSUE TITLE
Unable to download file

### ISSUE THREAD

**Issue by divija95** [ldbc/data-sets-surf-repository#3]
Hi,
I am unable to download files or request them as I am not affiliated with any of the institutes mentioned on the login site on SURF. Please let me know how I can access the files.

Thank you

**Comment by szarnyasg** [comment]
@divija95 you don't need to log in. Just click stage/download on the [data repository site](https://repository.surfsara.nl/datasets/cwi/snb) or [use the `download-data-set.sh`](https://github.com/ldbc/data-sets-surf-repository#usage) script.

**Comment by divija95** [comment]
Thank you for the quick response. I tried downloading, but the page says "Cannot download as zip: Not all files online".
When I run the automatic script for downloading, the following error appears:
$ ./download-data-set.sh https://repository.surfsara.nl/datasets/cwi/snb#
Preparing to download https://repository.surfsara.nl/datasets/cwi/snb#
Downloading data set
zstd: /*stdin*\: unsupported format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now

Please help.
Thank you

**Comment by szarnyasg** [comment]
@divija95 I clarified the README with a usage example: https://github.com/ldbc/data-sets-surf-repository#usage

```bash
./download-data-set.sh https://repository.surfsara.nl/datasets/cwi/snb/files/social_network-csv_basic-longdateformatter/social_network-csv_basic-longdateformatter-sf0.1.tar.zst
```

**Comment by divija95** [comment]
Thank you!

**Comment by scferrada** [comment]
> @divija95 I clarified the README with a usage example: https://github.com/ldbc/data-sets-surf-repository#usage
> 
> ```shell
> ./download-data-set.sh https://repository.surfsara.nl/datasets/cwi/snb/files/social_network-csv_basic-longdateformatter/social_network-csv_basic-longdateformatter-sf0.1.tar.zst
> ```

Hi, I've cloned this repo and copy-pasted this command and I'm getting the same error as divija95. This is the cli output:
```
Preparing to download https://repository.surfsara.nl/datasets/cwi/snb/files/social_network-csv_composite-longdateformatter/social_network-csv_composite-longdateformatter-sf10.tar.zst
Downloading data set
zstd: /*stdin*\: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Any ideas on what might be going on? Using the URLs of the other files produces the same output.

Thanks!

**Comment by szarnyasg** [comment]
Hello, surf was under maintenance today. The maintenance has now finished, so the script should work... if it doesnt't, please visit the surf website and try to stage them manually.

Gabor

**Comment by scferrada** [comment]
Thanks for the swift reply. There seems to be an issue with the SSL certificate of surf. I removed the `--silent` option from the call to `curl` in the script, and it returns the following:

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by szarnyasg** [comment]
Right. I'd just pass `--insecure` to `curl` to work around this for now. This is not binary data, just text, so it's unlikely to cause any harm.
