### ISSUE TITLE
Missing IS (short read) Substitution Parameters 

### ISSUE THREAD

**Issue by cw00dw0rd** [ldbc/data-sets-surf-repository#5]
The Substitution parameters currently only contain the BI and IC parameters but not the Interactive Short query parameters. Are there any current suggestions for those when using the surf datasets?

**Comment by szarnyasg** [comment]
@cw00dw0rd short query parameters are produced by the SNB Interactive driver based on the output of the complex reads. If you run your experiments without the driver (e.g. for microbenchmarking), my recommendation would be to randomly generate a random set of parameters. The short queries use either a `personId` or a `messageId` parameter as their input, so if you generate sequences of these, you can use them for your short queries.

**Comment by cw00dw0rd** [comment]
We have been using random values so far, but we are finding varying results based on the attribute we use. I suppose this is expected to some degree, but even with the IC parameters, the parameter we use from the substitution file can have notably different results. We can continue to use random values for the short reads, but this seems to go against the uniform approach that having the substitution parameters brings.

**Results Validation**
A related topic to choosing appropriate query parameters is determining valid/correct results, happy to create a separate issue if more appropriate.

For eventual auditing and result validation, would it be possible to add some criteria about the results returned? Such as, with queries that return a `person,` that person should have `x` number of friends or connections based on the specific query. 

Based on the specification document, I know that there is a consideration for this when generating data, but for sake of accuracy, perhaps some additional criteria could be added to validate the query results, even if this meant an additional query was required. This would help ensure results are consistent across vendors and would additionally help during the query-building process to ensure the results we receive match the intended results for each query.

**Comment by szarnyasg** [comment]
Hi, your observation is correct -- unfortunately, the current parameter generation often does not achieve its goal of generating query parameters that yield queries of similar difficulty. This is most obvious for the path queries, Q13 and Q14, where the source-destination pairs are sometimes selected from the same connected component (thus ensuring that path is found quickly) and sometimes from different components (which implies that the SUT has to "prove" that there is no path by doing e.g. a full search in the smaller connected component or running a CC algorithm on the entire graph). I have also seen a lot of variance for other queries.

For the SNB versions 0.x and 1.x, we do not plan to change the parameter generator, so the variants will stay and occur in audited results as well. However, for the upcoming v2.x version, we will rework it to ensure that the runtimes it produces are more predictable.

The same substitution parameters are for benchmarking and validation. Thinking about this, it would indeed be interesting to add parameters specifically for correctness testing, however, we currently do not have any plans to do so.

So currently the validation is best done against using the substitution parameters and one of the existing reference implementations such as Neo4j.
 
PS: If you are interested in auditing results in the near future (~next 6 months), please drop me an email and I can help you get started.
