### ISSUE TITLE
Server Error when attempting to download datasets

### ISSUE THREAD

**Issue by cw00dw0rd** [ldbc/data-sets-surf-repository#6]
Using curl I receive a small invalid file and when attempting to click the link via README I receive a 500 error.

**Comment by szarnyasg** [comment]
Hi @cw00dw0rd, SURF is under maintenance this morning. The maintenance timeframe is:
> Thursday August 25 09:00 until Thursday August 25 12:00 CEST.

**Comment by cw00dw0rd** [comment]
Ah ok thank you, I didn't think to look for the server status, is this viewable somewhere?

**Comment by szarnyasg** [comment]
I'm not sure whether there is a status page - I have not yet found it. I was informed through email about the maintenance.

**Comment by cw00dw0rd** [comment]
Ok thank you
