### ISSUE TITLE
Are Social Network Benchmark (SNB) Interactive datasets SF 3000 and SF10000 available? 

### ISSUE THREAD

**Issue by jasperzhong** [ldbc/data-sets-surf-repository#7]
Hi. We found this work by accident and appreciate you making these generated datasets publicly available. We are in need of large-scale temporal synthetic graphs to evaluate our system for dynamic graphs. The largest dataset we only found in the repo is SF1000, but we would like to have a larger graph. The SF3000 and SF10000 datasets are mentioned in the paper, but I could not find the links in this repo. Is there a download link for these two datasets? Thanks!

**Comment by szarnyasg** [comment]
Hi @jasperzhong, glad you found this benchmark!

* For Interactive v1 (inserts only), the largest SF is 1000. These are available in the SURF repository.

* For v2 (inserts+deletes), the BI data sets should be used. These are stored in Cloudflare R2.
https://github.com/ldbc/ldbc_snb_bi/blob/main/snb-bi-pre-generated-data-sets.md

    The update streams for Interactive v2 are being worked on – I'm running a generation job today for all SFs, if this succeeds, I'll upload them to R2.

**Comment by szarnyasg** [comment]
By the way, if you can use the temporal graphs for your work in their raw format (creationDate + deletionDate attributes), then you may consider using the raw data sets. These are available in Parquet format:

* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf1-raw.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf3-raw.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10-raw.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf30-raw.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf100-raw.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf300-raw.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf1000-raw.tar.zst.000
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf1000-raw.tar.zst.001
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf3000-raw.tar.zst.000
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf3000-raw.tar.zst.001
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf3000-raw.tar.zst.002
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf3000-raw.tar.zst.003
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.000
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.001
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.002
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.003
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.004
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.005
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.006
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.007
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.008
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.009
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.010
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/bi-raw/bi-sf10000-raw.tar.zst.011

**Comment by szarnyasg** [comment]
The update streams are available under the following links. The largest file (SF10,000) is 164 GB.

* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/interactive-updates/interactive-updates-sf1.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/interactive-updates/interactive-updates-sf3.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/interactive-updates/interactive-updates-sf10.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/interactive-updates/interactive-updates-sf30.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/interactive-updates/interactive-updates-sf100.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/interactive-updates/interactive-updates-sf300.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/interactive-updates/interactive-updates-sf1000.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/interactive-updates/interactive-updates-sf3000.tar.zst
* https://pub-383410a98aef4cb686f0c7601eddd25f.r2.dev/interactive-updates/interactive-updates-sf10000.tar.zst
