### ISSUE TITLE
Direct download links are not working

### ISSUE THREAD

**Issue by ayoubmoussaid** [ldbc/data-sets-surf-repository#8]
I keep recieving this error when trying to download the files: 
`{
code: 500,
error: "Internal error, if the problem persists please contact repository@surf.nl"
}`

**Comment by szarnyasg** [comment]
Hello @ayoubmoussaid - it's down for planned maintenance until Friday:

> due to planned maintenance on the SURF Data Archive, the service will be unavailable from Monday December 12 17:00 CET until Friday December 16 17:00 CET.

Are you looking for Graphalytics, BI or Interactive data sets? I have the first two mirrored in other repositories.

**Comment by ayoubmoussaid** [comment]
Oh okay, I didn't see that message anywhere. Thank you @szarnyasg

**Comment by ayoubmoussaid** [comment]
I need interactive datasets

**Comment by szarnyasg** [comment]
You can find them up to SF10:
https://surfdrive.surf.nl/files/index.php/s/aDjPSx089K06ViH
For the larger ones, unfortunately you have to wait until Friday or
generate them using the Hadoop Datagen:
https://github.com/ldbc/ldbc_snb_datagen_hadoop

**Comment by szarnyasg** [comment]
SURF's back: https://repository.surfsara.nl/datasets/cwi/snb
